/* eslint-disable @typescript-eslint/no-explicit-any */
import { Goat } from '../src/goat'
export { GoatResource, IAccount } from '../src/GoatResource'

export const goat: Goat

export * from './Alliance'
export * from './CouncilStatus'
export * from './Expeditions'
export * from './Feasts'
export * from './GameInfos'
export * from './HallOfFame'
export * from './Hero'
export * from './InLaw'
export * from './Item'
export * from './Kingdom'
export * from './Maidens'
export * from './Mail'
export * from './Misc'
export * from './Processions'
export * from './PunishmentResult'
export * from './RegularTasks'
export * from './Tourney'
export * from './TourneyDM'
export * from './TourneyXS'
export * from './User'
export * from './WeeklyRank'
export * from './WorldBoss'
export * from './Events'
export * from './Challenges'
