import { Account, Alchemy, Alliance, AllianceExperience, AllianceIntimacy, AllianceSiege, BlessedChest, Campaign, Children, Coronation, DarkCastle, Deathmatch, Divining, DragonSlaying, Expeditions, Feasts, GardenStroll, GiftingTree, GiftOfTheFae, Grain, HallOfFame, Heroes, HeroesTrial, Items, JewelsOfLuck, Kingdom, KingsPass, LimitedTimeQuests, MaidenExp, MaidenPainting, Maidens, Mail, PathOfWealth, PeoplesMonarch, Picnic, Processions, Profile, Quality, RaiseChildren, Rankings, Renovation, RenownedMerchant, Rewards, Shop, ThroneRoom, Tourney, TreasureHunt, VenetianPass, WorldBoss, XServerTourney } from './endpoints';
import { GoatConfig } from './AccountConfig';
export { GoatConfig };
export declare class Goat {
    private readonly _cookie;
    private readonly _host;
    private _version;
    protected _config: GoatConfig;
    isLoggedIn: boolean;
    account: Account;
    alliance: Alliance;
    campaign: Campaign;
    children: Children;
    expeditions: Expeditions;
    feasts: Feasts;
    hallOfFame: HallOfFame;
    heroes: Heroes;
    items: Items;
    kingdom: Kingdom;
    limitedTimeQuests: LimitedTimeQuests;
    maidens: Maidens;
    mail: Mail;
    processions: Processions;
    profile: Profile;
    rankings: Rankings;
    rewards: Rewards;
    shop: Shop;
    throneRoom: ThroneRoom;
    tourney: Tourney;
    worldBoss: WorldBoss;
    challenges: {
        xServerTourney: XServerTourney;
        deathmatch: Deathmatch;
        allianceSiege: AllianceSiege;
        allianceIntimacy: AllianceIntimacy;
        allianceExperience: AllianceExperience;
        grain: Grain;
        quality: Quality;
        maidenExp: MaidenExp;
        raiseChildren: RaiseChildren;
    };
    events: {
        alchemy: Alchemy;
        blessedChest: BlessedChest;
        castle: Renovation;
        coronation: Coronation;
        darkCastle: DarkCastle;
        divining: Divining;
        dragonSlaying: DragonSlaying;
        gardenStroll: GardenStroll;
        giftOfTheFae: GiftOfTheFae;
        giftingTree: GiftingTree;
        heroesTrial: HeroesTrial;
        jewelsOfLuck: JewelsOfLuck;
        kingsPass: KingsPass;
        maidenPainting: MaidenPainting;
        pathOfWealth: PathOfWealth;
        peoplesMonarch: PeoplesMonarch;
        picnic: Picnic;
        renownedMerchant: RenownedMerchant;
        treasureHunt: TreasureHunt;
        venetianPass: VenetianPass;
    };
    constructor(config?: GoatConfig | null);
    get host(): string;
    get cookie(): string;
    get version(): string;
    set version(version: string);
    get baseUrl(): string;
    get server(): string;
    set server(server: string);
    get gid(): string | null;
    get token(): string | null;
    get config(): GoatConfig;
    set config(config: GoatConfig);
    set login({ token, uid }: {
        token: any;
        uid: any;
    });
    _isGautier(): boolean;
    _logout(): void;
}
export declare const goat: Goat;
