import { Account, Alliance, Children, Expeditions, Feasts, HallOfFame, Items, Kingdom, Maidens, Mail, Processions, Profile, Rankings, Rewards, Tourney, WorldBoss, XServerTourney, Deathmatch, DarkCastle, GardenStroll, Picnic, TreasureHunt, Renovation, DragonSlaying, JewelsOfLuck } from './endpoints';
import { IAccount } from './GoatResource';
export { ACCOUNT_GAUTIER } from './accounts/gautier';
export { ACCOUNT_NAPOLEON } from './accounts/demophlos';
export { ACCOUNT_RAYMUNDUS } from './accounts/raymundus';
export declare class Goat {
    private readonly cookie;
    private token;
    private gid;
    private readonly host;
    private server;
    private version;
    private loginAccount;
    isLoggedIn: boolean;
    account: Account;
    alliance: Alliance;
    children: Children;
    expeditions: Expeditions;
    feasts: Feasts;
    hallOfFame: HallOfFame;
    items: Items;
    kingdom: Kingdom;
    maidens: Maidens;
    mail: Mail;
    processions: Processions;
    profile: Profile;
    rankings: Rankings;
    rewards: Rewards;
    tourney: Tourney;
    worldBoss: WorldBoss;
    challenges: {
        xServerTourney: XServerTourney;
        deathmatch: Deathmatch;
    };
    events: {
        darkCastle: DarkCastle;
        gardenStroll: GardenStroll;
        picnic: Picnic;
        treasureHunt: TreasureHunt;
        castle: Renovation;
        dragonSlaying: DragonSlaying;
        jewelsOfLuck: JewelsOfLuck;
    };
    constructor();
    _getHost(): string;
    _getCookie(): string;
    _getServer(): string;
    _setServer(server: string): this;
    _getVersion(): string;
    _setVersion(version: string): this;
    _getGid(): string | null;
    _setGid(gid: string): this;
    _getToken(): string | null;
    _setToken(token: string): this;
    _getBaseUrl(): string;
    _isGautier(): boolean;
    _getAccount(): IAccount;
    _setAccount(account: IAccount): this;
    _login({ token, uid }: {
        token: any;
        uid: any;
    }): void;
    _logout(): void;
}
export declare const goat: Goat;
