"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHILDREN_STATUS = void 0;
var CHILDREN_STATUS;
(function (CHILDREN_STATUS) {
    CHILDREN_STATUS[CHILDREN_STATUS["UNNAMED"] = 1] = "UNNAMED";
    CHILDREN_STATUS[CHILDREN_STATUS["GROWING"] = 2] = "GROWING";
    CHILDREN_STATUS[CHILDREN_STATUS["GROWNUP"] = 3] = "GROWNUP";
    CHILDREN_STATUS[CHILDREN_STATUS["EVALUATED"] = 4] = "EVALUATED";
    CHILDREN_STATUS[CHILDREN_STATUS["FINDING_SPOUSE"] = 5] = "FINDING_SPOUSE";
    CHILDREN_STATUS[CHILDREN_STATUS["MARRIED"] = 9] = "MARRIED";
})(CHILDREN_STATUS = exports.CHILDREN_STATUS || (exports.CHILDREN_STATUS = {}));
