"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TITLE = void 0;
var TITLE;
(function (TITLE) {
    TITLE[TITLE["MIGHT"] = 1] = "MIGHT";
    TITLE[TITLE["CHARM"] = 2] = "CHARM";
    TITLE[TITLE["CONQUERORS"] = 3] = "CONQUERORS";
    TITLE[TITLE["GLORY"] = 4] = "GLORY";
    TITLE[TITLE["ENLIGHTENMENT"] = 5] = "ENLIGHTENMENT";
    TITLE[TITLE["GRACE"] = 6] = "GRACE";
    TITLE[TITLE["ABUNDANCE"] = 7] = "ABUNDANCE";
    TITLE[TITLE["WARRIORS"] = 8] = "WARRIORS";
    TITLE[TITLE["PARAMOURS"] = 9] = "PARAMOURS";
    TITLE[TITLE["CHAMPIONS"] = 10] = "CHAMPIONS";
    TITLE[TITLE["WISDOM"] = 11] = "WISDOM";
    TITLE[TITLE["VIRTUE"] = 12] = "VIRTUE";
    TITLE[TITLE["CELEBRATION"] = 13] = "CELEBRATION";
    TITLE[TITLE["BEASTS"] = 14] = "BEASTS";
    TITLE[TITLE["AMBITION"] = 15] = "AMBITION";
})(TITLE = exports.TITLE || (exports.TITLE = {}));
