"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REWARD_PACKS = exports.RESOURCES_ITEMS = exports.ITEMS = void 0;
var ITEMS;
(function (ITEMS) {
    ITEMS[ITEMS["EXPERIENCE_PACK"] = 76] = "EXPERIENCE_PACK";
    ITEMS[ITEMS["SUP_EXPERIENCE_PACK"] = 78] = "SUP_EXPERIENCE_PACK";
    ITEMS[ITEMS["MANUSCRIPT_CACHE"] = 77] = "MANUSCRIPT_CACHE";
    ITEMS[ITEMS["MANUSCRIPT_PAGE"] = 111] = "MANUSCRIPT_PAGE";
    ITEMS[ITEMS["JEWELRY_BOX"] = 104] = "JEWELRY_BOX";
    ITEMS[ITEMS["FESTIVAL_BOX"] = 105] = "FESTIVAL_BOX";
    ITEMS[ITEMS["FAMED_HERO_FRAGMENT"] = 137] = "FAMED_HERO_FRAGMENT";
    ITEMS[ITEMS["FAMED_HERO_TOKEN"] = 126] = "FAMED_HERO_TOKEN";
    ITEMS[ITEMS["DUELING_FRAGMENT"] = 136] = "DUELING_FRAGMENT";
    ITEMS[ITEMS["DUELING_INVITATION"] = 131] = "DUELING_INVITATION";
    ITEMS[ITEMS["ALLIANCE_CHARTER"] = 128] = "ALLIANCE_CHARTER";
    ITEMS[ITEMS["ADV_ALLIANCE_CHARTER"] = 132] = "ADV_ALLIANCE_CHARTER";
    ITEMS[ITEMS["ALLIANCE_FRAGMENT"] = 135] = "ALLIANCE_FRAGMENT";
    ITEMS[ITEMS["ALLIANCE_SEAL"] = 723] = "ALLIANCE_SEAL";
    ITEMS[ITEMS["RUBY_RING"] = 160] = "RUBY_RING";
    ITEMS[ITEMS["RUBY_SCEPTER"] = 161] = "RUBY_SCEPTER";
    ITEMS[ITEMS["RUBY_SWORD"] = 162] = "RUBY_SWORD";
    ITEMS[ITEMS["HESSONITE_RING"] = 163] = "HESSONITE_RING";
    ITEMS[ITEMS["HESSONITE_SCEPTER"] = 164] = "HESSONITE_SCEPTER";
    ITEMS[ITEMS["HESSONITE_SWORD"] = 165] = "HESSONITE_SWORD";
    ITEMS[ITEMS["CITRINE_RING"] = 166] = "CITRINE_RING";
    ITEMS[ITEMS["CITRINE_SCEPTER"] = 167] = "CITRINE_SCEPTER";
    ITEMS[ITEMS["CITRINE_SWORD"] = 168] = "CITRINE_SWORD";
    ITEMS[ITEMS["EMERALD_RING"] = 169] = "EMERALD_RING";
    ITEMS[ITEMS["EMERALD_SCEPTER"] = 170] = "EMERALD_SCEPTER";
    ITEMS[ITEMS["EMERALD_SWORD"] = 171] = "EMERALD_SWORD";
    ITEMS[ITEMS["SAPPHIRE_RING"] = 172] = "SAPPHIRE_RING";
    ITEMS[ITEMS["SAPPHIRE_SCEPTER"] = 173] = "SAPPHIRE_SCEPTER";
    ITEMS[ITEMS["SAPPHIRE_SWORD"] = 174] = "SAPPHIRE_SWORD";
    ITEMS[ITEMS["AMETHYST_RING"] = 175] = "AMETHYST_RING";
    ITEMS[ITEMS["AMETHYST_SCEPTER"] = 176] = "AMETHYST_SCEPTER";
    ITEMS[ITEMS["AMETHYST_SWORD"] = 177] = "AMETHYST_SWORD";
    ITEMS[ITEMS["WAR_FUNDS"] = 65] = "WAR_FUNDS";
    ITEMS[ITEMS["CALL_TO_ARMS"] = 66] = "CALL_TO_ARMS";
    ITEMS[ITEMS["RATIONS"] = 67] = "RATIONS";
    ITEMS[ITEMS["WAR_BOND"] = 68] = "WAR_BOND";
    ITEMS[ITEMS["MERCENARY_CONTRACT"] = 69] = "MERCENARY_CONTRACT";
    ITEMS[ITEMS["TRIBUTE_CHEST"] = 79] = "TRIBUTE_CHEST";
    ITEMS[ITEMS["SUP_WAR_FUNDS"] = 87] = "SUP_WAR_FUNDS";
    ITEMS[ITEMS["PROVISIONS_TRIBUTE"] = 96] = "PROVISIONS_TRIBUTE";
    ITEMS[ITEMS["SOLDIERS_TRIBUTE"] = 97] = "SOLDIERS_TRIBUTE";
    ITEMS[ITEMS["SUP_PROVISIONS_TRIBUTE"] = 99] = "SUP_PROVISIONS_TRIBUTE";
    ITEMS[ITEMS["SUP_SOLDIERS_TRIBUTE"] = 100] = "SUP_SOLDIERS_TRIBUTE";
    ITEMS[ITEMS["RARE_RATIONS"] = 701] = "RARE_RATIONS";
    ITEMS[ITEMS["SMALL_REWARD_PACK"] = 260] = "SMALL_REWARD_PACK";
    ITEMS[ITEMS["REWARD_PACK"] = 261] = "REWARD_PACK";
    ITEMS[ITEMS["LARGE_REWARD_PACK"] = 262] = "LARGE_REWARD_PACK";
    ITEMS[ITEMS["NOBLE_REWARD_PACK"] = 263] = "NOBLE_REWARD_PACK";
})(ITEMS = exports.ITEMS || (exports.ITEMS = {}));
exports.RESOURCES_ITEMS = [
    ITEMS.WAR_FUNDS,
    ITEMS.CALL_TO_ARMS,
    ITEMS.RATIONS,
    ITEMS.WAR_BOND,
    ITEMS.MERCENARY_CONTRACT,
    ITEMS.TRIBUTE_CHEST,
    ITEMS.PROVISIONS_TRIBUTE,
    ITEMS.SOLDIERS_TRIBUTE,
    ITEMS.SUP_PROVISIONS_TRIBUTE,
    ITEMS.SUP_SOLDIERS_TRIBUTE,
    ITEMS.SUP_WAR_FUNDS,
    ITEMS.RARE_RATIONS,
];
exports.REWARD_PACKS = [
    ITEMS.SMALL_REWARD_PACK,
    ITEMS.REWARD_PACK,
    ITEMS.LARGE_REWARD_PACK,
    ITEMS.NOBLE_REWARD_PACK,
];
