"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CORONATION_ITEM = void 0;
var CORONATION_ITEM;
(function (CORONATION_ITEM) {
    CORONATION_ITEM[CORONATION_ITEM["BANNER"] = 1] = "BANNER";
    CORONATION_ITEM[CORONATION_ITEM["TRUMPET"] = 2] = "TRUMPET";
    CORONATION_ITEM[CORONATION_ITEM["DRUMS"] = 3] = "DRUMS";
    CORONATION_ITEM[CORONATION_ITEM["CROWN"] = 4] = "CROWN";
})(CORONATION_ITEM = exports.CORONATION_ITEM || (exports.CORONATION_ITEM = {}));
