"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PEOPLES_MONARCH_ITEM = void 0;
var PEOPLES_MONARCH_ITEM;
(function (PEOPLES_MONARCH_ITEM) {
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["BANNER"] = 1] = "BANNER";
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["TRUMPET"] = 2] = "TRUMPET";
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["DRUMS"] = 3] = "DRUMS";
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["CROWN"] = 4] = "CROWN";
})(PEOPLES_MONARCH_ITEM = exports.PEOPLES_MONARCH_ITEM || (exports.PEOPLES_MONARCH_ITEM = {}));
