"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PEOPLES_MONARCH_ITEM = void 0;
var PEOPLES_MONARCH_ITEM;
(function (PEOPLES_MONARCH_ITEM) {
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["CAP"] = 1] = "CAP";
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["SWORD"] = 2] = "SWORD";
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["ROSE"] = 3] = "ROSE";
    PEOPLES_MONARCH_ITEM[PEOPLES_MONARCH_ITEM["RING"] = 4] = "RING";
})(PEOPLES_MONARCH_ITEM = exports.PEOPLES_MONARCH_ITEM || (exports.PEOPLES_MONARCH_ITEM = {}));
